# Generated by Django 5.2.15 on 2026-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
